name: micro_gestion
description: Aplicación de gestión de inventario y ventas

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Paquetes esenciales
  http: ^1.2.2            # Para conexión con API
  shared_preferences: ^2.2.3  # Persistencia de datos
  provider: ^6.1.5        # Gestión de estado

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2   # Análisis de código

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png      # Carpeta para imágenes (opcional)